<?php

namespace Http\Docs;

use Package\ApiDocs\Generators\OpenApiGenerator;
use Tests\TestCase;

class DocsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $class = new \ReflectionClass(OpenApiGenerator::class);
        $class->setStaticPropertyValue('removeSuffixes', ['Resource', 'Controller']);
        $class->setStaticPropertyValue('removePrefixes', null);
    }

    /**
     * 测试公共文档接口
     *
     */
    public function testCommonApiDocsOne()
    {
        $commonApiDocs = $this->get('/api/docs/common-api');
        $commonApiDocs->assertStatus(200);
    }

    /**
     * 测试教师端后台文档接口
     *
     */
    public function testTeacherApiDocsOne()
    {
        $adminApiDocs = $this->get('/api/docs/teacher-api');
        $adminApiDocs->assertStatus(200);
    }

    /**
     * 测试学生端后台文档接口
     *
     */
    public function testStudentApiDocsOne()
    {
        $adminApiDocs = $this->get('/api/docs/student-api');
        $adminApiDocs->assertStatus(200);
    }
}
